//
// Created by caden.picard on 3/16/2025.
//
// This stuff autogenerated when I created the .cpp and .h files in CLion
#include "Animal.h"

// Nothing to implement here because constructors and methods are inline in the header.

// had to get gpt help on this. couldn't troubleshoot why my reference to Animal::MakeSound() was erroring
void Animal::makeSound() {
    // Empty definition because this is a pure virtual function
}

