//
// Created by caden.picard on 3/16/2025.
//
// This stuff autogenerated when I created the .cpp and .h files in CLion
#ifndef CAT_H
#define CAT_H
#include <iostream>
#include <string>

#include "Animal.h"

// Cat class - designed for the divas of the animal kingdom
class Cat :
    public Animal {
    public:
        // Default constructor cats do nothing
        Cat() {}

        // Parameterized constructor - for sassy cats with attitude
        explicit Cat(int id, std::string name, std::string shelter): Animal(id, name, shelter) {}

        // Overriding the makeSound() method - because cats own the world
        void makeSound() const;
};

inline void Cat::makeSound() const {
    std::cout << name << " says: Meow Meow!" << std::endl;
}

#endif // CAT_H
