//
// Created by caden.picard
//

// This stuff autogenerated when I created the .cpp and .h files in CLion
#ifndef HORSE_H
#define HORSE_H

#include <iostream>
#include <string>

#include "Animal.h"

// Horse class - every cowboy's dream
class Horse :

    public Animal {
    public:
        // Default constructor - does nothing, because sometimes horses just chill
        Horse() {}

        // Parameterized constructor - for majestic horses with IDs and cool names
        explicit Horse(int id, std::string name, std::string shelter):
            Animal(id, name, shelter) {}

        // Overriding the makeSound() method - because horses don't bark
        void makeSound() const;
};

inline void Horse::makeSound() const {
    std::cout << name << " says: Neigh Neigh!" << std::endl;
}


#endif //HORSE_H
